### ISSUE TITLE
Printmechecks Feature Requests

### ISSUE THREAD

**Issue by tkosaka3** [sktzofrenic/printmechecks#1]
Hi, thank you for creating this! I was wondering if I can request a few feature requests to enhance this?

1. Would it be possible to add a "Save" for the check and have it write to a log file? Then when you go back to the file, it'll recall the last check number, and add one to the check number so we don't accidentally reuse the same check number. Also a way to be able to view previous checks in case something happened to it, and reprint the check again if needed. 
2. For the signature, instead of the the font/fancy font, can we upload a transparent png of our signature on it?
3. For the memo line, can we make it so it can have multiple lines? That way with a windowed envelope, we can put the Payee's address there for easy mailing. 
4. Would it be possible to save multiple banking profiles? Like have one for My checking account, one for my wife's checking account and one for a joint checking account? And the same job of pulling the last saved check # +1 as in #1 for each profile. Also pull the correct signature image for each profile.

Thank you again!

**Comment by sktzofrenic** [comment]
I implemented some of these requests in 1.1. Hopefully it helps.
