### ISSUE TITLE
Bug: Page breaks due to toWords crash when check amount is blank or otherwise not a number

### ISSUE THREAD

**Issue by AySz88** [sktzofrenic/printmechecks#2]
Repro: Delete the dollar amount of the check, leaving the field blank. The function toWords crashes as "Not a Finite Number". The entire check preview and form disappear as a result, making it impossible to correct and resume without reloading and losing existing progress.

Experienced on the [demo](https://printmechecks.tiiny.site/).

My suggestion: Leave both the amount and amount-in-words line blank when this occurs, including removing the squiggle. If this is considered dangerous (as it creates a "blank check") fill it with zero or "VOID" instead.

**Comment by sktzofrenic** [comment]
Should be fixed in 1.1
