### ISSUE TITLE
Auto Set the Scale and Margins Properly as part of the Print Trigger

### ISSUE THREAD

**Issue by YisroelTech** [sktzofrenic/printmechecks#3]
Would it be possible to auto Set the Scale and Margins Properly as part of the Print Trigger, instead of having the user do it manually every time?

I found that simply adding styling while printing works for the Print button.

In Place of:
https://github.com/sktzofrenic/printmechecks/blob/6d824718d6e1073802c73a3bcda6dcf1833d8390/printmechecks/src/components/CheckPrinter.vue#L145-L147

Something like this:
```javascript
function printCheck () {
        // Apply print-specific styles
    const style = document.createElement('style');
    style.textContent = `
      @media print {
        @page {
          margin: 0;
        }
        body {
          transform: scale(1);
          transform-origin: top center;
          width: 149%;
          margin: 0;
          padding: 0;
        }
      }
    `;
    document.head.appendChild(style);

    // Trigger print
    window.print();

    // Clean up the added styles after printing
    style.remove();
}
```

What might be a tiny bit more difficult is adding a hook to redirect <kbd>Control</kbd> + <kbd>P</kbd> (which is generally simply doing the `window.print()`) to also use this added styling code. But it also seems to be possible with some hooks.

**Comment by sktzofrenic** [comment]
Looks good to me. I merged it.
